### ISSUE TITLE
please update to mongoid 5

### ISSUE THREAD

**Issue by antpaw** [Aethelflaed/mongoid-fixture_set#5]
just merge this https://github.com/djmolny/mongoid-fixture_set thanks (its not my repo)

**Comment by Aethelflaed** [comment]
It actually was a pull request: #4 
The changes in this repository does not fix your problem whatever it is.

I have `s.add_dependency 'mongoid', '>= 4.0'` in `mongoid-fixture_set.gemspec`, which includes mongoid 5 so it should work.

If you have any issue running this project with Mongoid 5, you're welcome to do any pull request you'd like.

I don't have much time to maintain this gem, and it has some design flaws at the moment... Feel free to contribute

**Comment by antpaw** [comment]
well okay, but you have never released this version.
https://github.com/Aethelflaed/mongoid-fixture_set/blob/v1.4.1/mongoid-fixture_set.gemspec
this is the newest gemspec that is submited to rubygems.org

**Comment by Aethelflaed** [comment]
You're right, sorry !
I just pushed the new version on rugygems
